harness/ff-java-server-sdk

- pom.xml
- src/main/java/io/harness/cf/client/api/Config.java
Change default eventURL for java sdk and make analyticsEnabled to true
> [FFM-687]: release 0.0.5

- pom.xml
> Releasing 0.0.6

- pom.xml
- src/main/java-templates/io/harness/cf/Version.java
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/Config.java
- src/main/java/io/harness/cf/client/api/DefaultApiFactory.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
- src/main/java/io/harness/cf/client/api/analytics/MetricsApiFactory.java
Make connectionTimout, readTimeout and writeTimeout configurable
Fix the version logic 
Fix nullpointerExceptions
> [FFM-756]: fix java sdk issues

- pom.xml
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
- src/main/java/io/harness/cf/client/dto/Target.java
also exclude invalid targets for metrics
> [FFM-756]: remove unwanted dependencies

- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/Config.java
- src/main/java/io/harness/cf/client/api/DefaultApiFactory.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsCacheFactory.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsManager.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
- src/main/java/io/harness/cf/client/api/analytics/GuavaCache.java
- src/main/java/io/harness/cf/client/api/analytics/TimerTask.java
Updating the blocking call in ringbuffer getNext to tryNext. 
Removing unwanted logs, adding a debug option in CfClient.
> [FFM-926]: updating code to make metrics service tracking a non blocking call

- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
minor change to how we name the global target for summarymetrics. Add global target to the target objectlist
> [FFM-1060]: Minor bugfix and change in name and identifier for the global target

- src/main/java/io/harness/cf/client/api/Evaluator.java
What:
Changed how rules are processed to ensure they are using the correct
attribute.
Added exclude rule processing, to ensure we can exclude targets
Refacatored code into two methods for readabiltiy
Why:
The rules for determining if a target belonged to segment were looking
at the wrong attribute value.  This means the rules were broken.
Previously we didn't evaluate the exclude list, so it wasn't possible to exclude
a target from a group.
> [FFM-1219]: Update clauses for processing segment match

- src/main/java/io/harness/cf/client/dto/SegmentBuilder.java
- src/main/java/io/harness/cf/client/dto/VariationMapBuilder.java
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
- src/test/java/io/harness/cf/client/api/mock/MockedAnalyticsHandler.java
The analytics tests were calling super() for overrided functions.  These didn't work in a mock
environment, so removed the call to super.
Added tests to the evaluator to test various rules
> (maint) Fixing broken tests and adding new tests for the evaluator

- README.md
- pom.xml
- template/pom.mustache
Version increased to 1.1.1 SNAPSHOT.
> 1.1.1-SNAPSHOT.

- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/Config.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/main/java/io/harness/cf/client/connector/Connector.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/main/java/io/harness/cf/client/connector/LocalConnector.java
- src/main/java/io/harness/cf/client/example/ConfigExample.java
- src/main/java/io/harness/cf/client/example/LegacyConfigExample.java
* Config is deprecated, BaseConfig is a new class for basic configuration
* Fixed NPE on notifyConsumers
> [FFM-1897] config for backward compatibility and minor bug fixed

- examples/pom.xml
- examples/src/main/java/io/harness/ff/examples/StressTest.java
- examples/src/main/resources/log4j.properties
- examples/src/main/resources/log4j2.xml
- pom.xml
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
Fix for the OkHttp library bug: closing that last known response.
> [FFM-3246]: Fixes OKHttp Library PollerProcessor Exception

- README.md
- docs/further_reading.md
- examples/src/main/java/io/harness/ff/examples/GettingStarted.java
* Added Getting Started Example, that is consistent with other SDKS
* Added Steps to run the example from CLI or with docker
> [FFM-3610]: Update docs with GettingStarted example

- examples/pom.xml
Update log4j version in examples/pom.xml
> FFM 4522 Git CVE update

- README.md
- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/Evaluator.java
Modify IN logic so that it evaluates the list of target groups and not just the first value.
> FFM-4744 Multiple target group conditions fix

- src/main/java/io/harness/cf/client/api/Evaluator.java
Change evaluation logic so that target group rules are treated as OR rather than AND.
> FFM-4808 Fix target group attribute condition OR

- README.md
- examples/pom.xml
- src/main/java/io/harness/cf/client/api/Evaluator.java
Fix percentage distribution to pass in percentages and then append
weight of variation.
> FFM-4830 Inconsistency in % of multivariate fix

- README.md
- pom.xml
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/SSEListener.java
```
[FFM-5149]: Feature flag API on CG manager returning inconsistent values
Adding logging to help trace the existing issue.
To help flag potential issues.
```
[FFM-5149]: https://harness.atlassian.net/browse/FFM-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-5149]: Feature flag API on CG manager returning inconsistent values

- .gitmodules
- README.md
- pom.xml
- src/main/java/io/harness/cf/client/api/CfClient.java
Amending log messages for version 1.0.5.3
> FFM-5188: Amending log messages

- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/test/java/io/harness/cf/client/api/MetricsProcessorTest.java
[FFM-5471] - Target identifier set in the target builder function in the Java SDK is not used
What
Targets reported by Java SDK are incorrectly showing in the UI Target Management -> Targets as the global target
Why
We're sending the global target identifier in the targetData when we shouldn't be. Also global target is not correctly applied to metricsData when isGlobalTargetEnabled is set
Testing
Tested manually with sample app to confirm changes are reflected in the UI. Also added a new unit test to capture and assert on the posted MetricsData object.
[FFM-5471]: https://harness.atlassian.net/browse/FFM-5471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-5471] - Target identifier set in the target builder function in the Java SDK is not used

- README.md
- examples/pom.xml
- pom.xml
What
Update public README.md to show latest released version
Change POM files on main to show SNAPSHOT for unreleased changes
> FFM-5912 - Update README.md and pom files

- README.md
- examples/pom.xml
- pom.xml
What
Bump version number in various files in preparation for release
> FFM-7277 - Release prep for Java SDK 1.2.2

- .gitignore
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/main/java/io/harness/cf/client/dto/Claim.java
* Add accountID and environmentIdentifier to Claims
* Add missing elements from the header
> FFM-7037: Add SDK type, version and lang to HTTP header

- README.md
- examples/pom.xml
- pom.xml
[FFM-9809] - 1.3.1 release prep
What
Update various metadata files for release 1.3.1
[FFM-9809]: https://harness.atlassian.net/browse/FFM-9809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9809] - 1.3.1 release prep

- build.gradle
- settings.gradle
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/api/StorageRepository.java
- src/main/java/io/harness/cf/client/common/Utils.java
- src/test/java/io/harness/cf/client/common/UtilsTest.java
FFM-10354 - Remove commons-collections4-4
**What**
Remove commons-collections4-4.4.jar
**Why**
Reduce SDK footprint. We only use 1 function `isEmpty()` but the JAR is 734.29 KB
**Testing**
Manual + testgrid
> FFM-10354 - Remove commons-collections4-4

- build.gradle
- settings.gradle
FFM-10356 - Remove threetenbp
**What**
Remove threetenbp dependency
**Why**
This dependency adds 501.64 KB and we don’t need it
**Testing**
Manual + testgrid
> FFM-10356 - Remove threetenbp

- build.gradle
- settings.gradle
FFM-10361 - Add Gradle dependency-check plugin
**What**
Add plugin for scanning for CVEs via `gradle dependencyCheckAnalyze`
**Testing**
Manual
> FFM-10361 - Add Gradle dependency-check plugin

- src/main/java/io/harness/cf/client/api/Evaluator.java
**What**
Updates the previous commit to add a check so we don't return true when there are no clauses
> [FFM-10861] - Fix for previous commit

- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/common/SdkCodes.java
- src/test/java/io/harness/cf/client/api/EvaluatorIntegrationTest.java
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
- src/test/java/io/harness/cf/client/common/SdkCodesTest.java
**What**
Adds the ability to configure if SDK code 6001 (default variation served) should be supressed.
**Why**
Some customers want to know when a default was served, other don't need it. So make it configurable.
**Testing**
Manual + unit
> [FFM-11425] - Add config option to supress SDK code 6001
