- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/Config.java
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsManager.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
- src/main/java/io/harness/cf/client/api/analytics/MetricsApiFactory.java
- src/main/java/io/harness/cf/client/dto/Target.java
- src/main/java/io/harness/cf/client/example/Example.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
This change introducse a new url endpoint for the metrics server.
This means the metric server can be deployed independently of the client server.
This commit also addresses a bug where the analytics service may not be initalized
if we failed to validate the API key.
The Target custom field has been renamed attributes
> Support Metrics Service Endpoint

- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
This change fixes 2 issues:
* The varation is a string and cant be casted to a JSONObject it needs to be parsed.
* When a flag was off we returned the varation name rather than the variation value.
> FFM-728: Support JSON variations

- pom.xml
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
- src/main/java/io/harness/cf/client/dto/Analytics.java
Currently we do not send the variation identifier in the metricsService. This enhancement will send variationIdentifier as well as the variationValue in the metrics data. We will deprecate the featureValue attribute in the subsequent releases.
> [FFM-842]: adding support for variation identifier in the analyticsService

- src/main/java/io/harness/cf/client/api/analytics/AnalyticsManager.java
This changes the type of the parameter passed from Object to Variation to
avoid an invalid cast problem.
> (FFM-842) Change the parameter from object to variation

- pom.xml
This is to address vulnerability in the library that is being used by jjwt-jackson. The latest version of this library has not been released which has the fix
> Updating jackson dependency

- src/main/java/io/harness/cf/client/Example.java
- src/main/java/io/harness/cf/client/api/AuthService.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
- src/main/java/io/harness/cf/client/dto/Target.java
Also added a helper method for targetbuilder attributes and privateAttributes so we can pass in single values rather than entire maps and sets
> [FFM-1060]: remove variation value from being published to the metrics server

- src/main/java/io/harness/cf/client/api/Evaluator.java
What:
When a flag is being evaluated, that has been direcltly added to a segment,
we now call `isTargetIncludedBySegment()`  to ensure we check the
include, exclude and custom rules for matching targets to segments.
Why:
Previously we only checked if a target was matched to a segment with the include list.
We didn't evaluate the exclude list or custom rules.
> [FFM-1356]: Determine if a target should be included in a segment

- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/DefaultApiFactory.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsManager.java
- src/main/java/io/harness/cf/client/api/analytics/AnalyticsPublisherService.java
- src/main/java/io/harness/cf/client/api/analytics/MetricsApiFactory.java
- src/test/java/io/harness/cf/client/api/mock/MockedAnalyticsManager.java
- src/test/java/io/harness/cf/client/api/mock/MockedCfClient.java
Currently the analytics manager enables a copy of the client API on startup,
however this is a static instance.
The problem when debug is enabled, that the manager didn't read the config, and so tries
to modify the static instance of the client API from a different thread (setting it to false, where as the main thread as set it to true).
This results in the manager throwing an exception and failing to start.
As a by product the isInitalize function will never return true.
What:
This change removes the second intialization of the static client API.  The client API is initalized from
the main constructor, so will already exist.
Instead of the analytics manager authenticating seperately it shares the same JWT as the the client API.
> [FFM-1358]: Analytics manager fails to start when debug is enabled

- src/main/java/io/harness/cf/client/api/Evaluator.java
Debug messages were displaying %s instead of the values, 
fixed to use `String.format()` like other instances found in the repository, and removed redundant "\n" - logger adds new lines for each message.
other option is to use {} to get the logger auto replacement, it is more recommended IMO, but prefered to go with repo standard.
issue sample from log 
```
10:40:59.092 [main] DEBUG io.harness.cf.client.api.Evaluator - Target %s included in segment %s via rules
```
> Small fix values of log.debug messages

- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
What:
Use toString() instead of a cast to string
Why:
Target attributes are stored as there native type and converted to an Object
in java.
We were using a cast to convert them to a string representation to use in the
evaluator.
This failed silently as an exception was throw.  We need to use the toString()
method to correctly get the string representation of the attribute value.
Tests:
Added some unit tests to cover this
> [FFM-1446]: Rules processing for integer and boolean types failed

- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/test/java/io/harness/cf/client/api/FFUseCaseTest.java
When clause field 'attribute' is empty and segmentMatch operator always return false
* Now it first checks operator segmentMatch and return evaluated value
* Then it checks other operators
> [MAINT] fix segments includes

- src/test/java/io/harness/cf/client/api/EvaluatorIntegrationTest.java
- src/test/java/io/harness/cf/client/api/FFUseCaseTest.java
- src/test/java/io/harness/cf/client/api/TestCase.java
Currently the evaluation tests output the test driver method name
i.e. 'runTestCase'
When adding new test cases it can be hard to see what test is actually running/failing.
This change introduces a test name.
After tests run the name should be inserted as the testcase name in the XML output i.e.
<testcase name="test_empty_or_missing_target_attributes" classname="io.harness.cf.client.api.FFUseCaseTest" time="0.009">
> [FFM-2680]: Tests should generate user friendly testname

- src/main/java/io/harness/cf/client/api/Evaluator.java
This change uses the Optional.ofNullable, which handles the null and
returns empty.
This change also removes the reflection when used to lookup the name
and identifier fields of a target.
When attempting to access an attribute in a map, which does not exist
a null was being passed to the Optional.of function.
This caused a NPE.
A evaluation test was added to simulate this case.
> [FFM-2680]: Fix NPE when checking attributes map

- examples/src/main/java/io/harness/ff/examples/GettingStarted.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
Added conditional to check for enableAnalytics in processEvaluation
function. Should now prevent from queueing metrics data when
analyticsEnabled is set to false.
Will add tests at a later time as discussed.
> FFM-3694 Fix enableAnalytics

- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/main/java/io/harness/cf/client/api/SummaryMetrics.java
Previously we were just sending globalTarget name, but now it can be configured to send the actual target by using globalTargetEnabled. Defaults to true.
> FFM 4399 Configurable targets

- pom.xml
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/test/java/io/harness/cf/client/api/MetricsProcessorTest.java
- src/test/resources/logback-test.xml
Pushing a lot of metric events to the MetricsProcessor can result in: java.lang.OutOfMemoryError: unable to create new native thread
When the LinkedBlockingQueue fills up, a thread is triggered to drain the events. However the call to executor() which is part of AbstractScheduledService actually creates a new thread via newSingleThreadScheduledExecutor on each call. When lots of events are pushed this caused submit() to be called many times each creating new thread - eventually till the JVM runs out of native memory.
Added a new unit test to push 100k metrics on a metrics queue with a small size (10). This test fails without the fix applied.
> FFM-4849 - Thread leak in MetricsProcessor

- pom.xml
- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/api/MetricEvent.java
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/test/java/io/harness/cf/client/api/MetricsProcessorTest.java
- src/test/resources/logback-test.xml
This PR changes the way we store the metrics and reduces memory as the previous method was storing too much and/or redundant data which caused the metrics processor potential out of memory errors. 
The changes are as follows:
- Changed from blocked queue to AtomicLongMap;
- Also includes various other cleanups and changes
- Updated unit test to test more permutations, added synchronized to runOneIteration()
> FFM-4396 Change Metrics

- pom.xml
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/PollingProcessor.java
- src/main/java/io/harness/cf/client/common/ScheduledServiceStateLogger.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/main/java/io/harness/cf/client/connector/HarnessConfig.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
**What**
SSE client should avoid using a read timeout of 0 since if the socket is not gracefully shutdown we have no way to detect that the socket is dead. Instead enforce a default read time out > 0 to force the connection to refresh and remove any stale socket. This change integrates the original bug fix FFM-5149 from 1.0.5.X into main. Main has previsouly been refactored and diverged so a 1:1 merge is not possible so a re-implementation has been done.
Additional changes:
- okhttp bumped from 3.9.1 to 4.9.0 to match 1.0.5.X version
- sseTimeout is now defined in HarnessConfig since Config was deprecated
- Fixed an issue where Poller would not restart on SSE disconnect due to the starttime not being set
- Added additional logging around socket events and ScheduledService states 
**Why** …
> FFM-5251 - Merge FFM-5149 (flags out of sync) from 1.0.5.X to main

- .github/workflows/pr_maven.yaml
- README.md
- examples/pom.xml
- pom.xml
What
- Update version numbers on pom.xml files for 1.1.6
- Bump minor versions of dependencies to get latest bug fixes and security updates
Why
To allow published artifacts to have the correct version number.
Testing
Tested manually with ff-java-server-sample against app.harness.io, ensured flags are retrieved ok and metrics are being sent back.
> FFM-5298 - Java SDK release 1.1.6 prep

- src/test/java/io/harness/cf/client/api/EvaluatorIntegrationTest.java
FFM-5306 - Updating git sub module to use latest ff-test-cases + fix for test JSON parsing code
What
Update the Java SDK's ff-test-cases to get latest changes for prereq tests. Also fixes a bug in the test's JSON parsing code where we only loaded the current flag instead of all of them.
Why
Make sure we're using the latest tests in the ff-test-cases drone project.
Testing
Unit tests passed for EvaluatorIntegrationTest with latest JSON
> FFM-5306 - Updating git sub module to use latest ff-test-cases

- pom.xml
- src/test/java/io/harness/cf/client/api/EvaluatorIntegrationTest.java
What
Allow Java SDK test cases to be run from any subfolder inside ff-test-cases if it ends with a JSON extension
Why
This will allow converted test cases to run which may be nested in folders
Testing
Tested manually with some test folders and unknown files
> FFM-5389 - Java SDK - Add recursion when scanning ff-test-cases folder

- README.md
- pom.xml
- src/test/java/io/harness/cf/client/api/EvaluatorIntegrationTest.java
- src/test/java/io/harness/cf/client/api/FFUseCaseTest.java
FFM-5389 - Adding JUnit5Xml30StatelessReporter to get dynamic tests reported in surefire reports
What
Adding extension JUnit5Xml30StatelessReporter so we can see dynamic test names in surefire reports.
Also fixed readme which is mentioning an unreleased version
Why
All test cases for dynamic tests are showing getTestCases(), we want to see the actual name of the dynamic test
Testing
Tested manually, checked XML output of surefire was showing more than just getTestCase
> FFM-5389 - Adding JUnit5Xml30StatelessReporter

- pom.xml
[FFM-5247] Fix Jacoco code coverage report
What
Fix the Jacoco code coverage plugin to correctly generate coverage reports. Surefire plugin will stomp over the command line arguments needed by Jacoco and they need to be preserved with some additional configuration.
Why
We want to be able to generate Jacoco code coverage reports so that downstream pipelines can consume coverage information for better reporting
Testing
Confirmed target/jacoco.exec and ./target/site/jacoco/index.html exists after building via cmd line
[FFM-5247]: https://harness.atlassian.net/browse/FFM-5247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-5247] Fix Jacoco code coverage report

- README.md
- examples/pom.xml
- examples/src/main/java/io/harness/ff/examples/GettingStarted.java
- pom.xml
FFM-5928 - Fix java.lang.NoSuchMethodError caused by conflicting versions of kotlin-stdlib on the classpath
What
Exclude kotlin-stdlib being brought in by mapdb.
Minor fix to GettingStart example to stop it from closing the client too soon.
Why
okhttp 4.9.3 uses a newer version of the kotlin-stdlib which is conflicting with a version brought in by mapdb
Testing
Tested with GettingStarted java sample using same instructions as on the README
> FFM-5928 - Fix java.lang.NoSuchMethodError caused by kotlin-stdlib 

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/connector/HarnessConfig.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
FFM-5910 - Don't mask exceptions reported during authentication
What
If we get any exceptions during authentication, make sure the stack trace is logged to make it easier to diagnose issues.
Why
During testing of the testgrid load test framework SDK hung due to a classpath conflict so authentication did not complete (and no error was reported because the exception was swallowed)
Testing
Tested against the ff-sdk-testgrid java container
> FFM-5910 - Don't mask exceptions reported during authentication

- pom.xml
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
- src/test/java/io/harness/cf/client/api/TestUtils.java
- src/test/resources/local-test-cases/basic_bool_string_number_json_variations.json
FFM-5247 - Java SDK - Improve unit test coverage (CfClient)
What
Increase unit test coverage on CfClient and related classes. Add new tests to bring some classes above 70% coverage
Why
Our coverage is low in certain areas
Testing
All tests pass in IntelliJ and on command line
> FFM-5247 - Java SDK - Improve unit test coverage (CfClient)

- README.md
- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
FFM-6125 - Nullpointer in MetricsProcessor
What
When passing in a null target to an xxxVariation() function we get a NullPointerException. This change fixes the MetricsProcessor to handle nulls correctly and corrects a log statement to use toString() instead of deferencing target directly.
Why
Logger statement and metrics processing code don't perform any null checks.
Testing
Unit testing: added new unit tests to check that nulls can be passed in without error. Manual testing with GettingStarted sample
> FFM-6125 - Nullpointer in MetricsProcessor

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
- src/test/java/io/harness/cf/client/api/TestUtils.java
- src/test/java/io/harness/cf/client/api/dispatchers/CannedResponses.java
- src/test/java/io/harness/cf/client/api/dispatchers/TestWebServerDispatcher.java
- src/test/java/io/harness/cf/client/api/dispatchers/UnimplementedStreamDispatcher.java
FFM-5111 - Java SDK - Polls non stop if /stream endpoint returns 5xx error
What
If a /stream endpoint returns a 501 HTTP error code (unimplemented) then the SSE library attempts reconnect endlessly
Why
The code is assuming 501 is a transient http error - so keeps retrying it rather than backing off for good
Testing
Added new mock web server dispatcher to mimic a 501 response when /stream is connected to. New assertion were added to ensure SDK doesn't attempt to reconnect once when a 501 is returned.
[FFM-5111]: https://harness.atlassian.net/browse/FFM-5111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FFM-5111 - Java SDK - Polls non stop if /stream endpoint returns 5xx error

- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
- src/test/java/io/harness/cf/client/api/MetricsProcessorStressTest.java
- src/test/java/io/harness/cf/client/api/testutils/DummyConnector.java
FFM-6392 - Java SDK - Investigate thread contention MetricsProcessor.pushToQueue
What
- Remove synchronized keyword from pushToQueue (also renamed to registerEvaluation)
- Remove synchronized keyword from runOneIteration, instead a new method was added to drain frequencyMap atomically which means we no longer need synchronized here
- Remove debug logs causing excessive string concat operations in pushToQueue as reported by profiler
- New stress test added to place load on this method with multiple threads, for easier profiling
Why
Platform team are reporting contention around MetricsProcessor.pushToQueue with JFR when using a large number of targets and flags.
Testing
Tested manually with new junit stress test added for MatricsProcessor with list of targets/flags used by platform.
> FFM-6392 - Java SDK - Investigate thread contention MetricsProcessor.pushToQueue

- README.md
- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/PollingProcessor.java
- src/main/java/io/harness/cf/client/connector/ConnectorException.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/main/java/io/harness/cf/client/connector/RetryInterceptor.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
- src/test/java/io/harness/cf/client/api/TestUtils.java
- src/test/java/io/harness/cf/client/api/dispatchers/CannedResponses.java
- src/test/java/io/harness/cf/client/api/dispatchers/Endpoints.java
- src/test/java/io/harness/cf/client/api/dispatchers/Http4xxOnFirstAuthDispatcher.java
- src/test/java/io/harness/cf/client/api/dispatchers/Http4xxOnGetAllSegmentsDispatcher.java
- src/test/java/io/harness/cf/client/api/testutils/PollingAtomicLong.java
- src/test/java/io/harness/cf/client/connector/HarnessConnectorUtils.java
- src/test/resources/logback-test.xml
What
- Fixed RetryInterceptor to close response & remove old fix
- Fixed 403 re-authentication logic to correctly restart auth service
- Added new tests for returning and asserting 4xx codes
- ConnectionException to now stores HTTP code and reason for better logging + removed some excessive logging
Why
java.lang.IllegalStateException "cannot make a new request because the previous response is still open" is seen when the endpoint returns a 4xx error. Due to connection not being closed correctly in retry interceptor.
Testing
New unit tests added in CfClientTest for testing 4xx reponses + manual testing
> FFM-6442 - Java SDK - java.lang.IllegalStateException logged by okhttp

- README.md
- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/UpdateProcessor.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/test/java/io/harness/cf/client/api/dispatchers/CannedResponses.java
- src/test/java/io/harness/cf/client/connector/CountingUpdater.java
- src/test/java/io/harness/cf/client/connector/EventSourceTest.java
- src/test/resources/logback-test.xml
FFM-6581 - Java SDK - Poller was not restarted + timeouts logged
What
Fixed timeout exception, reduce some log levels to debug and added additional unit tests.
Why
We see timeout errors logged becauses the code calls awaitTermination() before shutDown() when stopping the update processor. Also we log misleading warnings about poller not being restarted when in fact the code is working as intented (though it's candidate for additional optimisation in future releases).
Testing
Added new unit tets for EventSource + manual testing
> FFM-6581 - Java SDK - Poller was not restarted + timeouts logged

- src/main/java/io/harness/cf/client/api/AuthCallback.java
- src/main/java/io/harness/cf/client/api/AuthService.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/connector/ConnectorException.java
Also only wait for 5 seconds instead of forever, allowing the failure check to propagate and for the app to shutdown
I ran into a few issues with the SDK when I had put in the wrong apiKey. So this PR just improves that failure case
> Add broader exception handling in case authentication fails

- examples/pom.xml
- examples/src/main/java/io/harness/ff/examples/TlsExample.java
- examples/src/main/resources/log4j.properties
- examples/src/main/resources/log4j2.xml
- pom.xml
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/main/java/io/harness/cf/client/connector/HarnessConfig.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/test/java/io/harness/cf/client/connector/EventSourceTest.java
FFM-7004 - Java SDK - TLS - support custom CAs
What
Allow the SDK user to provide a custom TLS CA via the HarnessConnector API
Why
We currently rely on pre-installed CA bundles in the JDK for TLS connections, e.g. those hostnames signed by public CAs, it's useful to provide alternative methods of loading private TLS CAs for internal on-prem deployments
Testing
Manual - tested against a ff-server proxy with TLS termination enabled
> FFM-7004 - Java SDK - TLS - support custom CAs

- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
What
Add Harness-SDK-Info header to outbound HTTP connections
Why
Helps with diagnosing issues on the backend
Testing
Manual - tested with a proxy that logs headers
> FFM-7038 - Add SDK info header

- README.md
- examples/src/main/java/io/harness/ff/code_cleanup_examples/README.md
- examples/src/main/java/io/harness/ff/code_cleanup_examples/SampleClass.java
- examples/src/main/java/io/harness/ff/code_cleanup_examples/config/rules.toml
**Changes**
Add an example of using the flag cleanup drone plugin to the java sdk repo.
A user can follow the instructions to run the docker container from the code_cleanup_examples directory to see the if else block for STALE_FLAG being removed. 
```
docker run -v ${PWD}:/java-sdk -e PLUGIN_DEBUG=true -e PLUGIN_PATH_TO_CODEBASE="/java-sdk" -e PLUGIN_PATH_TO_CONFIGURATIONS="/java-sdk/config" -e PLUGIN_LANGUAGE="java" -e PLUGIN_SUBSTITUTIONS="stale_flag_name=STALE_FLAG,treated=true,treated_complement=false" harness/flag_cleanup:latest
```
Extra docs on how adapt this example and configure this for your own custom repo will be added next week in the main https://github.com/harness/flag_cleanup repo.
> (FFM-7131) Add flag cleanup example

- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/main/java/io/harness/cf/client/common/StringUtils.java
- src/main/java/io/harness/cf/client/connector/FileWatcher.java
- src/main/java/io/harness/cf/client/dto/Target.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
- src/test/java/io/harness/cf/client/common/StringUtilsTest.java
In support of  #143 to remove Guava as a dependency this remove the usage of `Strings.isNullOrEmpty` and `ImmutableSet.of`
These methods are just a few lines of simple code that can be self contained in the Java SDK
Unit test added for StringUtils.isNullOrEmpty
> Reduce Guava usage (in preparation for removal)

- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/api/Query.java
Addresses #142 
This makes the `Evaluator` class and `Query` interface public, allowing users to instantiate their own instances.
Since the `cache` is already injectable, it can be reused with a users own instance of the `Evaluator` class. So if a user can instantiate their own instance of the `Evaluator` class, they can do evaluations on all flags, without triggering metric reporting.
This is needed in my case since we send pre-evaluated flags to the browser to do some simple JS based feature flagging.
No testing is needed, this merely open up classes for instantiation.
> Open the Evaluator and Query class/interfaces to allow usage

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/PollingProcessor.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/test/java/io/harness/cf/client/connector/EventSourceTest.java
FFM-5915 - Remove oksse dependency
What
Remove oksse dependency and use okhttp-sse instead. Added a retry inteceptor since okhttp-see does not provide any backoff/retry support
Why
We're getting reports of customers having difficulty running the SDK because of missing dependency oksse. oksee was only ever published once to 1 repository and has not been mirrored globally, this means that unless the user has the exact repo in their POM/Gradle file (JitPack) they will more often than not hit this problem at compile time.
Testing
Unit tests + manual proxy
> FFM-5915 - Remove oksse dependency

- pom.xml
What
Update maven-model dependency to 3.5.0 to remove CVE-2022-4245
> FFM-8133 - Java SDK - Update maven-model dependency to 3.5.0

- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
FFM-7037: Additional header fixes
What
Fixes blank headers. Headers need to be set after the auth token arrives not before
Testing
Tested with local proxy
> FFM-7037: Additional header fixes

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/Evaluator.java
FFM-6412 - Flags with multiple prerequisites evaluating incorrectly
What
Fix prerequisites loop in the evaluator code
Why
Only the first parent feature is being processed by the evalator due to the loop exiting too early.
Testing
TestEvaluations_ServerSDK + unit tests passing
The following server evaluation tests now pass with this fix:
Custom_SDK_:_Type=BoolWith2JSON;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOff;Return_False
Custom_SDK_:_Type=BoolWith2JSON;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOnToo;Return_False
Custom_SDK_:_Type=BoolWith2Str;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOnToo;Return_False
Custom_SDK_:_Type=BoolWith2Bool;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOnToo;Return_False …
> FFM-6412 - Flags with multiple prerequisites evaluating incorrectly

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
- src/test/java/io/harness/cf/client/api/dispatchers/CannedResponses.java
- src/test/java/io/harness/cf/client/api/dispatchers/JwtMissingFieldsAuthDispatcher.java
- src/test/java/io/harness/cf/client/connector/HarnessConnectorTest.java
[FFM-8688] - Handle accountID as an optional field in the JWT token
What
Adding new unit tests + harden the existing JWT parsing code to handle information which may be optional when an ff-proxy is in use. If the info is not available the header will not be added. Also fixed env header to fall back to UUID when not present.
Why
The proxy doesn’t send accountID in the JWT token on auth, so we should make sure the code handles this correctly without bailing out when a proxy is in use.
Testing
New unit tests written + manual
[FFM-8688]: https://harness.atlassian.net/browse/FFM-8688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-8688] - Handle accountID as an optional field in the JWT token

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/AuthService.java
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/main/java/io/harness/cf/client/api/PollingProcessor.java
- src/main/java/io/harness/cf/client/common/SdkCodes.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/main/java/io/harness/cf/client/connector/LocalConnector.java
- src/main/java/io/harness/cf/client/connector/Updater.java
- src/test/java/io/harness/cf/client/common/SdkCodesTest.java
- src/test/java/io/harness/cf/client/connector/CountingUpdater.java
- src/test/java/io/harness/cf/client/connector/EventSourceTest.java
[FFM-8148] - Standardise SDK error codes
What
Adding standardised SDK error codes + pushing some logs down to debug to reduce noise
Why
Each SDK uses different log messages for its lifecycle. We want to standardise messages across SDKs with a unique code.
Testing
Manual testing + unit testing
[FFM-8148]: https://harness.atlassian.net/browse/FFM-8148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-8148] - Standardise SDK error codes

- src/main/java/io/harness/cf/client/connector/LocalConnector.java
- src/test/java/io/harness/cf/client/connector/LocalConnectorTest.java
[FFM-4023] - JavaSDK local connector doesn't create metrics folder
**What**
Fixes exception reported by LocalConnector when sub-folders are missing.
**Why**
LocalConnector needs flags, segments, metrics and a domain folder to exist before writing to them.
**Testing**
New unit test
[FFM-4023]: https://harness.atlassian.net/browse/FFM-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-4023] - JavaSDK local connector doesn't create metrics folder

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/connector/FileWatcher.java
[FFM-9691] - Add support for Java 21
What
Java 21 was released in Sep 2023 and is an LTS release. Update the relevant files.
Why
The current version of the Java SDK uses some APIs which are now deprecated (via lombok) and causes the build to fail on latest JDK.
Testing
Manual
[FFM-9691]: https://harness.atlassian.net/browse/FFM-9691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9691] - Add support for Java 21

- examples/code_cleanup_examples/SampleClass.java
- examples/src/main/java/io/harness/ff/examples/EventExample.java
- examples/src/main/java/io/harness/ff/examples/Example.java
- examples/src/main/java/io/harness/ff/examples/ExcessiveLogs.java
- examples/src/main/java/io/harness/ff/examples/Local.java
- examples/src/main/java/io/harness/ff/examples/Simple.java
- examples/src/main/java/io/harness/ff/examples/Singleton.java
- examples/src/main/java/io/harness/ff/examples/StressTest.java
- examples/src/main/java/io/harness/ff/examples/TryWithRes.java
- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/dto/Target.java
[FFM-9482] - Mark private attributes for removal
What
Add deprecated tags to private attributes so they can be removed in a future release
[FFM-9482]: https://harness.atlassian.net/browse/FFM-9482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9482] - Mark private attributes for removal

- pom.xml
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/UpdateProcessor.java
- src/main/java/io/harness/cf/client/common/Utils.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/test/java/io/harness/cf/client/api/CfClientTest.java
- src/test/resources/logback-test.xml
[FFM-9809] - Adding additional tests for reset streams
What
Update EventSource to call onDisconnect() and add new logic to restart SSE. Adds another test to CfClientTest that will force a stream to drop during data transfer
Why
Additional assertions are useful for testing code paths
Testing
Unit test
[FFM-9809]: https://harness.atlassian.net/browse/FFM-9809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9809] - Improved stream restart logic

- examples/pom.xml
- pom.xml
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/java/io/harness/cf/client/common/SdkCodes.java
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
[FFM-9924] - Testgrid - % rollout - Java SDK - Fix MM3 hash
**What**
Various fixes to MM3 hash to bring it in alignment with GoLang SDK
- Set MM3 seed to 0
- If bucket_by attribute is missing, fall back to identifier + log new SDK code
- Additional debug statements for easier diagnostics
- Update unit tests
**Why**
Review SDKs to make sure Murmur3 hash calculations are consistent across SDKs and buckets mappings align for customers that rely on this feature.
**Testing**
New percentage rollout tests added to testgrid, these will be committed later
[FFM-9924]: https://harness.atlassian.net/browse/FFM-9924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9924] - Testgrid - % rollout - Java SDK - Fix MM3 hash

- src/main/java/io/harness/cf/client/connector/EventSource.java
[FFM-10136] - Drop SSE event log down from INFO to DEBUG
**What**
Change SSE event log from INFO to DEBUG
**Why**
Remove excessive logging at INFO level
**Testing**
Manual
[FFM-10136]: https://harness.atlassian.net/browse/FFM-10136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-10136] - Drop SSE event log down from INFO to DEBUG

- build.gradle
- settings.gradle
- src/main/java/io/harness/cf/client/connector/LocalConnector.java
FFM-10355 - Remove maven-model
**What**
Remove maven-model and its dependencies to save approx 871 KB
commons-lang3-3.5.jar   468.63 KB
plexus-utils-3.0.24.jar 241.55 KB
maven-model-3.5.0.jar   161.15 KB
**Why**
We only use the class `ImmutablePair` from commons-lang3 which can be easily re-implemented
**Testing**
Manual + testgrid
> FFM-10355 - Remove maven-model

- build.gradle
- settings.gradle
FFM-10363 - Upgrade okhttp and fix CVE-2023-3635, CVE-2022-24329 & CVE-2020-29582
**What**
Upgrade okhttp to 4.12.0
**Why**
The following dependencies have CVEs: `kotlin-stdlib-1.4.10.jar` and `okio-2.8.0.jar` these are brough in by okhttp 4.9.3, we should upgrade to 4.12.0
https://nvd.nist.gov/vuln/detail/CVE-2023-3635
https://nvd.nist.gov/vuln/detail/CVE-2022-24329
https://nvd.nist.gov/vuln/detail/CVE-2020-29582
**Testing**
Manual + testgrid
> FFM-10363 - Upgrade okhttp and fix CVE-2023-3635, CVE-2022-24329 & CVE-2020-29582

- src/main/java/io/harness/cf/client/api/UpdateProcessor.java
- src/main/java/io/harness/cf/client/connector/ConnectorException.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/test/java/io/harness/cf/client/api/UpdateProcessorTest.java
FFM-10366 - Delete events throwing ApiException exception
**What**
Delete events don't need to call out to the server since they're only a notification to remove a flag/segment from local cache.
**Why**
When deleting a flag or target segment the following exception is seen:
```
io.harness.cf.ApiException:
at io.harness.cf.ApiClient.handleResponse(ApiClient.java:1079)
at io.harness.cf.ApiClient.execute(ApiClient.java:992)
at io.harness.cf.api.ClientApi.getSegmentByIdentifierWithHttpInfo(ClientApi.java:1087)
at io.harness.cf.api.ClientApi.getSegmentByIdentifier(ClientApi.java:1062)
at io.harness.cf.client.connector.HarnessConnector.getSegment(HarnessConnector.java:334)
at io.harness.cf.client.api.UpdateProcessor.lambda$processSegment$1(UpdateProcessor.java:124)
at …
```
> FFM-10366 - Delete events throwing ApiException exception

- README.md
- examples/src/main/java/io/harness/ff/examples/GettingStarted.java
[FFM-10981] - Update Java SDK example to include a delay
**What**
The example on the main page is missing a `sleep()` statement that is included in the code example. This updates the main page to match the example code.
**Why**
Help avoid confusion around the life cycle of the SDK - the current example will exit immediately which is not what we want.
[FFM-10981]: https://harness.atlassian.net/browse/FFM-10981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-10981] - Update Java SDK example to include a delay

- build.gradle
- settings.gradle
- src/main/java/io/harness/cf/client/api/Evaluator.java
- src/main/resources/client-v1.yaml
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
- src/test/resources/local-test-cases/v2-andor-flags.json
- src/test/resources/local-test-cases/v2-andor-segments.json
[FFM-11193] - Target v2: Adding support for AND/OR in clauses
**What**
Adding support for processing the new `GroupServingRule` in `Segment`. Also update API definition for OpenAPIGenerator plugin. The default behaviour now is to check for the existence of `GroupServingRule` if found then we ignore the old `Rules` section. Old `Rules` section will continue to work to aid transition if `GroupServingRule` is not yet populated. Each entry in `GroupServingRule` is ORed while each item in `clauses` is ANDed. The `GroupServingRule` with the highest priority used first to allow reordering on the UI.
**Why**
This gives the customer more flexibility on how they configure their rules in the backend.
**Testing**
Initial unit tests for now + testgrid will come later
[FFM-11193]: …
> [FFM-11193] - Target v2: Adding support for AND/OR in clauses

- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/main/resources/client-v1.yaml
- src/test/java/io/harness/cf/client/api/dispatchers/Endpoints.java
- src/test/java/io/harness/cf/client/api/dispatchers/TestWebServerDispatcher.java
FFM-11356 - Add new query parameter to target-segments
**What**
Adds a new query parameter to tell the BE which rule JSON format the SDK is capable of handling locally
**Why**
Caching can be performed on the BE by keying on the URL
**Testing**
Manual + proxy
> FFM-11356 - Add new query parameter to target-segments

- settings.gradle
**What**
Update to latest BC since STO is breaking the build
**Why**
STO is flagging CVE-2024-34447, CVE-2024-29857, CVE-2024-30171, CVE-2024-30172
**Testing**
Manual
> [FFM-11502] - Update BC to 1.78.1

- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/Query.java
- src/main/java/io/harness/cf/client/api/StorageRepository.java
- src/test/java/io/harness/cf/client/api/EvaluatorIntegrationTest.java
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
- src/test/java/io/harness/cf/client/api/StorageRepositoryTest.java
- src/test/java/io/harness/cf/client/api/TestUtils.java
- src/test/resources/local-test-cases/basic_bool_string_for_repository.json
```
[FFM-11846] : Store and delete previous version of the FeatureConfig along with the new one.
Store and retrieve current and previous version of the feature config.
Delete both versions of the config.
Added tests
To meet customer's requirements.
Locally + unit tests
```
[FFM-11846]: https://harness.atlassian.net/browse/FFM-11846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-11846] : Store and delete previous version of the FeatureConfig along with the new one in cache

- examples/build.gradle
- examples/src/main/java/io/harness/ff/examples/EventExampleWithFeatureSnapshot.java
- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- Added configuration flag to the base config. 
- Added public client functions to get the snapshots
- If snapshot disabled, we will log in the message in the debug and return snapshot containing only current version.
> [FFM-11845]: Extend relevant constructors to enable storing previous and current FeatureConfig

- README.md
- build.gradle
- examples/build.gradle
- examples/src/main/java/io/harness/ff/examples/EventExampleWithFeatureSnapshot.java
- settings.gradle
- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/api/CfClient.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/Query.java
- src/main/java/io/harness/cf/client/api/StorageRepository.java
- src/main/resources/client-v1.yaml
- src/test/java/io/harness/cf/client/api/EvaluatorIntegrationTest.java
- src/test/java/io/harness/cf/client/api/EvaluatorTest.java
- src/test/java/io/harness/cf/client/api/StorageRepositoryTest.java
- src/test/java/io/harness/cf/client/api/StoreRepositoryBenchmark.java
- src/test/java/io/harness/cf/client/api/TestUtils.java
- src/test/resources/local-test-cases/basic_bool_string_for_repository.json
Added ability to store and retrieve feature snapshot, containing both previous and current version of the feature config.
> [FFM-1844]: FeatureSnapshot for JavaSDK

- README.md
- examples/src/main/java/io/harness/ff/examples/ConfigExample.java
- settings.gradle
- src/main/java/io/harness/cf/client/api/BaseConfig.java
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/MetricsProcessor.java
- src/main/java/io/harness/cf/client/connector/Connector.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/main/java/io/harness/cf/client/connector/HarnessConfig.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/main/java/io/harness/cf/client/connector/LocalConnector.java
- src/main/java/io/harness/cf/client/connector/NewRetryInterceptor.java
- src/test/java/io/harness/cf/client/api/MetricsProcessorStressTest.java
- src/test/java/io/harness/cf/client/api/MetricsProcessorTest.java
- src/test/java/io/harness/cf/client/api/testutils/DummyConnector.java
- src/test/java/io/harness/cf/client/connector/EventSourceTest.java
This PR adds two new features, and fixes some bugs around closing the SDK.
- Adds new `maxRequestRetry` option, defaulting to `10`, which controls the number of retries made for requests to `auth` / `polling` / `metrics` / `fetch flag` and `fetch group` requests
- Changes the stream reconnect limit from `5` attempts to no limit. This was a bug, and to align with our SDKs the stream should always attempt to reconnect (on retryable errors)
- Exponential backoff capped at 1 minute max delay.
- Adds new BaseConfig option `flushAnalyticsOnClose`, defaulting to `disabled`, which will post analytics when the SDK is closed. The default timeout for this request is `30000ms`, before which the SDK will not be fully closed and network resources used by the request will remain open.  
- Adds new …
> FFM-12087 New configuration options + close related bug fixes

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
We're currently publishing to Legacy OSSRH which goes away on June 30th, update Gradle publish plugin to use Central Portal instead.
See https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/
> feat: [FFM-12481]: Migrate to Maven Central Portal

- settings.gradle
- src/main/java/io/harness/cf/client/api/InnerClient.java
- src/main/java/io/harness/cf/client/api/PollingProcessor.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/main/java/io/harness/cf/client/connector/NewRetryInterceptor.java
Release 1.8.0 inadvertently increased the noise in the logs when the SDK is repeatedly shutdown. With that change, we now check if a shutdown is in progress and if so, it aborts any inflight requests with a generic reset/cancel error. This reset/cancel request inadvertently gets logged which causes misleading endpoint logs. This changes removes that noise.
- Avoid logging disconnect errors on shutdown
- Log additional stack traces for diagnostics
- Fixed polling log to make it more unique
> fix: [FFM-12506]: Avoid logging endpoint errors if SDK is shutting down

- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- src/main/java/io/harness/cf/client/connector/DelegatingSocketFactory.java
- src/main/java/io/harness/cf/client/connector/EventSource.java
- src/main/java/io/harness/cf/client/connector/HarnessConnector.java
- src/main/java/io/harness/cf/client/connector/ProxyConfig.java
- Adding (experimental) support for http proxy properties via properties: `http(s).proxyHost`,  `http(s).proxyPort`,  `http.proxyUser` and `http.proxyPassword`. The current implementation passes these directly to okhttp.
> feat: [FFM-12489]: Adding support for HTTP proxies

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Update various dependencies to remove the following CVEs
```
commons-lang3-3.14.0.jar (pkg:maven/org.apache.commons/commons-lang3@3.14.0, cpe:2.3:a:apache:commons_lang:3.14.0:*:*:*:*:*:*:*) : CVE-2025-48924
gson-2.10.jar (pkg:maven/com.google.code.gson/gson@2.10, cpe:2.3:a:google:gson:2.10:*:*:*:*:*:*:*) : CVE-2025-53864
gson-2.11.0.jar (pkg:maven/com.google.code.gson/gson@2.11.0, cpe:2.3:a:google:gson:2.11.0:*:*:*:*:*:*:*) : CVE-2025-53864
logback-core-1.3.14.jar (pkg:maven/ch.qos.logback/logback-core@1.3.14, cpe:2.3:a:qos:logback:1.3.14:*:*:*:*:*:*:*) : CVE-2024-12798, CVE-2024-12801
```
> fix: [FFM-12578]: Fixes various CVEs
